


name = "PushOps"

default_targets = ["win32", "win64"]
build_directory = "makelove-build"

love_files = [
    "::git-ls-tree::",
    "-*/.*",
]


[win32]

shared_libraries = [
    "release/Steam/luasteam_SO/win32/luasteam.dll",
    "release/Steam/steam_SO/win32/steam_api.dll",
    "release/Steam/steam_SO/win32/steam_api.lib"
]


[win64]

shared_libraries = [
    "release/Steam/luasteam_SO/win64/luasteam.dll",
    "release/Steam/steam_SO/win64/steam_api64.dll",
    "release/Steam/steam_SO/win64/steam_api.lib",
]


[appimage]

shared_libraries = [
    "release/Steam/luasteam_SO/linux64/luasteam.so",
    "release/Steam/steam_SO/linux64/libsteam_api.so"
]

artifacts = "appimage"





[macos]

[macos.app_metadata]
CFBundleName = "PushOps"
CFBundleIdentifier = "tld.PushOps"
NSHumanReadableCopyright = "Copyright 2021-2022 Oliver Garrett"
CFBundleShortVersionString = "PushOps 1.0"


shared_libraries = [
    "release/Steam/luasteam_SO/osx/luasteam.so",
    "release/Steam/steam_SO/osx/libsteam_api.dylib"
]


